### ISSUE TITLE
Feature: VARA?

### ISSUE THREAD

**Issue by driechers** [craigerl/digipi#12]
I have VARAHF working on my digipi with varanny to use radio mail on my ios devices and to work with pat. I'd be happy to polish it up and merge in if you would like. Disclaimer though:

- Vara is closed source yucky
- It runs in Wine, double yucky

If these are cool with you, I'll take the time to polish it up, get it printing out on the display, put in web page updates, etc so its not customized to just my usage. What do you think?

**Comment by craigerl** [comment]
... and x86 emulation,  all together, doesn't fit on the $15 piZero2W/512MB budget.   so Pi4/Pi5 only.

I'd like to see a process documented somewhere, but I'm not licensed to re-distribute the closed-source software, so it'd be more of a "contrib" add on?

cool,
-craig
KM6LYW

**Comment by driechers** [comment]
Makes perfect since. Too much yuck and I didn't consider license. I will throw something up on my github with my script and crude install steps then drop a link in here. It did involve a bit of hacking to get it all working.

**Comment by driechers** [comment]
Here you go! Crude instructions and a rant on my confusion and frustration with close source software nonsense :smile: 

Thanks for the awesome work you have done with digipi! I have some ideas in my own backlog of fun stuff to hopefully contribute.

https://github.com/driechers/VARA-HF-digipi/blob/main/README.md
