### ISSUE TITLE
Feature Request: Toggle between Shack Location, GPS Input, or Temporary Location

### ISSUE THREAD

**Issue by askpatrickw** [craigerl/digipi#2]
Because many GPS enabled radios (and other devices) cannot get a GPS lock indoors, switching between a static location (Home) or using the Real-Time location would be a great feature.

In addition being able to update a static location without starting over with your image would be helpful.

I think a drop-down would be ideal:
- Home Location (configured at Setup)
- GPS Location
- Temporary Location -- Which would then display an input box to input a location. I'm not sure if must be lat lon or grid square.

**Comment by craigerl** [comment]
Cool.  Which apps specifically?   digipeaters?   js8/ft8?  others?

**Comment by askpatrickw** [comment]
If it was done that way, I think you'd want to do it for the whole DigiPi, update the location in all the places.. 


However, the right way to do this, might be to switch my radio (IC-705) between GPS and Manual mode... gotta test that.

**Comment by askpatrickw** [comment]
This needs a lot more thought, I'm going to close it for now.
